"""
Django settings for application project.

Generated by 'django-admin startproject' using Django 1.11.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import sys

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 's(i036-r_9svgk@-fc-3+zczrsl&&+-!1blyknp@3ne^vjsk_p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'web-app',
    '172.18.0.4',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'core.apps.CoreConfig',
    'likes.apps.LikesConfig',
    'rating.apps.RatingConfig',
    'task.apps.TaskConfig',
    'userman.apps.UsermanConfig',
    'categories.apps.CategoriesConfig',
    'comments.apps.CommentsConfig',
    'crispy_forms',
    'debug_toolbar',
    'social_django',
    'corsheaders',
]

AUTH_USER_MODEL = 'core.User'

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True

INTERNAL_IPS = [
    '127.0.0.1',
]

CASHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '127.0.0.1:11211',
    }
}

ROOT_URLCONF = 'application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'core.context_processors.main',
            ],
        },
    },
]

WSGI_APPLICATION = 'application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
    }
}

AUTHENTICATION_BACKENDS = (
    'social_core.backends.vk.VKOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
TESTING = 'test' in sys.argv

if TESTING:
    DATABASES['default'] = {'ENGINE' : 'django.db.backends.sqlite3'}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


CRISPY_TEMPLATE_PACK = 'bootstrap4'

#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATICFILES_DIRS = ('static', )

FIXTURE_DIRS = (
   '/fixtures/',
)

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#STATICFILES_STORAGE = 'django.core.files.storage.FileSystemStorage'

AWS_S3_ENDPOINT_URL = "http://hb.bizmrg.com"
AWS_ACCESS_KEY_ID = 'oupF5S8BAVPEeq3Bgx8SBR'
AWS_SECRET_ACCESS_KEY = 'fBo4C7U3dLpScJHJSAftyAQRLi89DaZkAYktuhRUb9wx'
AWS_STORAGE_BUCKET_NAME = 'jokerety'


SOCIAL_AUTH_VK_OAUTH2_KEY = '6723065'
SOCIAL_AUTH_VK_OAUTH2_SECRET = 'o2noxhbLsMmRlPVhbyKT'

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = '668911897522-9fanv0uqm64reeebr3ncdblu10kei9v6.apps.googleusercontent.com'
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = 'GhzQeZvtuqJeO5XcbrNicb_w'

LOGIN_REDIRECT_URL = '/categories/'
LOGIN_URL = '/login/'
SOCIAL_AUTH_VK_OAUTH2_SCOPE = ['email']
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = ['email']


CENTRIFUGE_ADDRESS = 'http://localhost:9000'
CENTRIFUGE_SECRET = 'bd90eb08-e145-40ee-a390-02d0146e9918'
CENTRIFUGE_API_KEY = 'kk2l234h-92fj-pwfd-okp4-124g44b43d33'
CENTRIFUGE_TIMEOUT = 10

