# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
