# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='viewcount',
            field=models.IntegerField(default=0),
        ),
    ]
