# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-19 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userfile'),
        ('task', '0007_task_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.ManyToManyField(to='core.UserFile'),
        ),
    ]
