version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: docker_basa
      MYSQL_USER: docker_user
      MYSQL_PASSWORD: 2346785das

  web-app:
    depends_on: [ db ]
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=docker_basa
      - DB_HOST=db
      - DB_USER=docker_user
      - DB_PASSWORD=2346785das

  centrifugo:
    image: centrifugo/centrifugo:latest
    command: centrifugo -c /centrifugo/centrifugo.json --port=9000 --admin
    volumes:
      - ./configs/config.json:/centrifugo/centrifugo.json
    restart: always
    ports:
      - 9000:9000

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080
    links:
      - web-app
      - centrifugo

  frontend:
    build:
      context: ../../2018-FS-21-Frontend-RomanMaslov/
    command: npm start
    volumes:
      - ../../2018-FS-21-Frontend-RomanMaslov/:/app
      - /app/node_modules
    depends_on:
      - web-app
    ports:
      - 3000:3000
    links:
      - web-app


